---
- name: ensure nginx-mantlui docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ mantlui_nginx_image }}:{{ mantlui_nginx_image_tag }}
  tags:
    - mantlui
    - bootstrap

- name: configure nginx-mantlui
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-mantlui.service.j2
      dest: /usr/lib/systemd/system/nginx-mantlui.service
    - src: nginx-mantlui.env.j2
      dest: /etc/default/nginx-mantlui.env
  notify:
    - reload nginx-mantlui
    - restart nginx-mantlui
  tags:
    - mantlui

- name: enable nginx-mantlui
  sudo: yes
  service:
    name: nginx-mantlui
    enabled: yes
    state: started
  notify:
    - restart nginx-mantlui
  tags:
    - mantlui

- name: create directory for health check
  file: path=/usr/share/mesos/webui/master/static/js/ state=directory mode=0755
  sudo: yes

- name: create file controllers.js for health check
  copy:
    content: ""
    dest: /usr/share/mesos/webui/master/static/js/controllers.js
  sudo: yes

- name: create file services.js for health check
  copy:
    content: ""
    dest: /usr/share/mesos/webui/master/static/js/services.js
  sudo: yes

- name: create file app.js for health check
  copy:
    content: ""
    dest: /usr/share/mesos/webui/master/static/js/app.js
  sudo: yes
