---
- name: install utilities for DC/OS
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
  tags:
    - dcos

- name: Create group 'nogroup'
  sudo: yes
  group: name=nogroup state=present


- name: Disable IPv6 for all interfaces
  sudo: yes
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes

- name: Disable IPv6 for default interface
  sudo: yes
  sysctl: name="net.ipv6.conf.default.disable_ipv6" value=1 sysctl_set=yes
