---
- name: install utilities for DC/OS
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
  tags:
    - dcos

- name: create group 'nogroup'
  sudo: yes
  group: name=nogroup state=present
  tags:
    - dcos

- name: disable IPv6 for all interfaces
  sudo: yes
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes
  tags:
    - dcos

- name: disable IPv6 for default interface
  sudo: yes
  sysctl: name="net.ipv6.conf.default.disable_ipv6" value=1 sysctl_set=yes
  tags:
    - dcos
