---
- name: install DC/OS agent
  shell: cd /tmp/dcos-install/genconf/serve/; sudo bash dcos_install.sh slave --disable-preflight
  sudo: yes
  ignore_errors: yes
  tags:
    - dcos

- set_fact: colon=":"
  tags:
    - dcos

- name: change UDP port for spartan
  lineinfile:
    dest=/opt/mesosphere/etc/spartan.json
    regexp="  \"udp_port.*"
    line="  \"udp_port\"{{colon}} 553,"
    state=present
  sudo: yes
  tags:
    - dcos

- name: change TCP port for spartan
  lineinfile:
    dest=/opt/mesosphere/etc/spartan.json
    regexp="  \"tcp_port.*"
    line="  \"tcp_port\"{{colon}} 553"
    state=present
  sudo: yes
  tags:
    - dcos
