---
# Prepare the directories and download installation file

- name: Clear install directory
  sudo: yes
  file: path=/tmp/dcos-install/ state=absent
  ignore_errors: true

- file: path=/tmp/dcos-install state=directory mode=0755
- file: path=/tmp/dcos-install/genconf/ state=directory mode=0755
- get_url: url="{{ dcos_download }}" dest=/tmp/dcos-install/dcos_generate_config.sh mode=0440

# Create IP detection script
- template: src=ip-detect-aws.j2 dest=/tmp/dcos-install/genconf/ip-detect mode=0644
  when: provider == "aws"
- template: src=ip-detect-gce.j2 dest=/tmp/dcos-install/genconf/ip-detect mode=0644
  when: provider == "gce"
- template: src=ip-detect-eth0.j2 dest=/tmp/dcos-install/genconf/ip-detect mode=0644
  when: provider == "eth0"

# Generate DC/OS configuration file
- template: src=config-static.yaml.j2 dest=/tmp/dcos-install/genconf/config.yaml mode=0644
  when: exhibitor == "static"

# Generate Rexray configuration file
- template: src=rexray.yaml.j2 dest=/tmp/dcos-install/genconf/rexray.yaml mode=0644
  when: rexray_config_method == "file"

# Generate DC/OS bootstrap files
- shell: bash dcos_generate_config.sh chdir=/tmp/dcos-install/
  sudo: yes

# Install DC/OS Agent
- shell: cd /tmp/dcos-install/genconf/serve/; sudo bash dcos_install.sh slave --disable-preflight
  sudo: yes
  ignore_errors: yes


# - name: install follower configuration
#   sudo: yes
#   yum:
#     name: "{{ mesos_agent_package }}"
#     state: present
#   tags:
#     - mesos
#     - bootstrap
#
# - name: configure mesos-agent
#   sudo: yes
#   template:
#     src: mesos-agent.sysconfig.j2
#     dest: /etc/sysconfig/mesos-agent
#   notify: remove mesos follower metadata
#   tags:
#     - mesos
#
# - name: write credential
#   when: do_mesos_follower_auth|bool
#   sudo: yes
#   copy:
#     dest: /etc/sysconfig/mesos-agent-credential
#     content: "{{ mesos_follower_principal }} {{ mesos_follower_secret }}"
#     mode: 0600
#   notify: restart mesos follower
#   tags:
#     - mesos
#
# - name: delete credential
#   when: not do_mesos_follower_auth|bool
#   sudo: yes
#   file:
#     dest: /etc/sysconfig/mesos-agent-credential
#     state: absent
#   notify: restart mesos follower
#   tags:
#     - mesos
#
# - name: write mantl-api credential
#   when: do_mesos_framework_auth|bool
#   sudo: yes
#   template:
#     src: mantl-api-credential.j2
#     dest: /etc/sysconfig/mantl-api
#     mode: 0600
#   tags:
#     - mesos
#
# - name: delete mantl-api credential
#   when: not do_mesos_framework_auth|bool
#   sudo: yes
#   file:
#     dest: /etc/sysconfig/mantl-api
#     state: absent
#   tags:
#     - mesos
