---
- name: install DC/OS master
  shell: cd /tmp/dcos-install/genconf/serve/; sudo bash dcos_install.sh master --disable-preflight
  sudo: yes
  ignore_errors: yes
  tags:
    - dcos

- set_fact: colon=":"
  tags:
    - dcos

- name: change UDP port for spartan
  lineinfile:
    dest=/opt/mesosphere/etc/spartan.json
    regexp="  \"udp_port.*"
    line="  \"udp_port\"{{colon}} 553,"
    state=present
  sudo: yes
  tags:
    - dcos

- name: change TCP port for spartan
  lineinfile:
    dest=/opt/mesosphere/etc/spartan.json
    regexp="  \"tcp_port.*"
    line="  \"tcp_port\"{{colon}} 553"
    state=present
  sudo: yes
  tags:
    - dcos

- name: change default HTTP port for adminrouter
  lineinfile: dest=/opt/mesosphere/active/adminrouter/nginx/conf/nginx.conf regexp=".*listen [0-9]+ default_server;" line="        listen 8000 default_server;" state=present
  sudo: yes
  tags:
    - dcos

- name: change default HTTPS port for adminrouter
  lineinfile: dest=/opt/mesosphere/active/adminrouter/nginx/conf/nginx.conf regexp=".*listen [0-9]+ ssl spdy default_server;" line="        listen 8443 ssl spdy default_server;" state=present
  sudo: yes
  tags:
    - dcos

- name: create directory for dc/os cli
  file: path=/opt/dcos-cli state=directory mode=0755
  sudo: yes
  tags:
    - dcos

- name: download pip
  get_url: url="https://bootstrap.pypa.io/get-pip.py" dest=/opt/dcos-cli/get-pip.py mode=0440
  sudo: yes
  tags:
    - dcos

- name: install pip
  shell: python /opt/dcos-cli/get-pip.py
  args:
    executable: /bin/bash
  sudo: yes
  tags:
    - dcos

- name: install virtualenv
  shell: pip2.7 install virtualenv
  args:
    executable: /bin/bash
  sudo: yes
  tags:
    - dcos

- name: download dc/os cli
  get_url: url="https://downloads.dcos.io/dcos-cli/install.sh" dest=/opt/dcos-cli/install.sh mode=0744
  sudo: yes
  tags:
    - dcos

- name: wait until dc/os is ready
  wait_for: host=localhost port=8000 delay=10 state=present
  tags:
    - dcos

- name: install dcos cli
  shell: bash ./install.sh . http://leader.mesos:8000 --add-path yes
  args:
    chdir: /opt/dcos-cli/
  sudo: yes
  tags:
    - dcos
